# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('schedules', models.TextField(blank=True, null=True)),
                ('valet_parking', models.BooleanField(default=False)),
                ('auto_service', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('restrooms', models.BooleanField(default=False)),
                ('credit_cards', models.BooleanField(default=False)),
                ('reservations', models.BooleanField(default=False)),
                ('outdoor_seats', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('delivery', models.BooleanField(default=False)),
                ('to_take_away', models.BooleanField(default=False)),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='venues.Category')),
            ],
        ),
    ]
