# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20170827_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='mapped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mapped_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
