# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20170827_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='denied_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
