# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20170819_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='secondary_names',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
