# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 20:16
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_secondary_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='position',
            field=geoposition.fields.GeopositionField(default=None, max_length=42),
            preserve_default=False,
        ),
    ]
